### ISSUE TITLE
FindInstructions.py IDA6.9

### ISSUE THREAD

**Issue by flyninja** [idapython/src#8]
~~~~~~
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "../idapython/Scripts/FindInstructions.py", line 134, in find
    c.choose()
  File "..\IDA 6.9\python\idaapi.py", line 49405, in choose
    self.icon)
TypeError: in method 'choose_choose', argument 1 of type 'void *'
Script Default snippet error: Traceback (most recent call last):
  File "<string>", line 45, in <module>
  File "..\IDA 6.9\python\idaapi.py", line 49405, in choose
    self.icon)
TypeError: in method 'choose_choose', argument 1 of type 'void *'
~~~~~~

**Comment by aundro** [comment]
Hi,

Please direct all bug reports to <support@hex-rays.com>.
Concerning this particular issue: we are aware of it, and it was fixed (but not yet pushed here). Please contact us for a hotfix, while I'm preparing the patch for this repository. Thanks!
